import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Contact from '@/components/Contact'
import App from '@/widgets/App'
import Home from '@/components/Home'

const inter = Inter({ subsets: ['latin'] })

export default function Hero() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/portfolio.ico" />
      </Head>

      <Header />

      <Home />
      <About />
      <Experience />
      <Contact />
      <Footer />

    </>
  )
}
